# Generated by Django 5.1.6 on 2025-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('pageview', 'Page View'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('scroll_depth', 'Scroll Depth')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('url', models.URLField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('referrer', models.URLField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_name'], name='api_event_event_n_90a521_idx'), models.Index(fields=['timestamp'], name='api_event_timesta_28a369_idx'), models.Index(fields=['path'], name='api_event_path_52daa8_idx'), models.Index(fields=['country'], name='api_event_country_d17262_idx')],
            },
        ),
    ]
